services:
  pihole-exporter:
    container_name: pihole-exporter
    build:
      context: .
      dockerfile: Dockerfile.exporter
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PORT=80
      - PIHOLE_PASSWORD=
      - PIHOLE_PROTOCOL=http
      - PIHOLE_CONTAINER=pihole
      - EXPORTER_PORT=9617
      - USE_VOLUME_MOUNT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - pihole_network
    ports:
      - "9617:9617"
    restart: unless-stopped
    depends_on:
      pihole:
        condition: service_healthy

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - pihole_network
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - pihole-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - pihole_network
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

  pihole:
    container_name: pihole
    image: docker.io/pihole/pihole:latest
    env_file:
      - .env.pihole
    networks:
      - pihole_network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "8443:443/tcp"
    volumes:
      - config_dnsmasq:/etc/dnsmasq.d
      - config_pihole:/etc/pihole
      - ./certs/tls.pem:/etc/pihole/tls.pem:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  config_dnsmasq:
    driver: local
  config_pihole:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  pihole_network:
    driver: bridge
